name: publish-action

on:
  release:
    types: [published]

jobs:
  publish-action:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Placeholder
        run: echo "publish to GitHub Marketplace gated on tag"
